name: auth_mock_3
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.2
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.10
  cloud_firestore: ^3.1.17
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flutter_triple: ^1.2.7+2
  asuka: ^2.0.0+1
  iconly: ^1.0.1
  flutter_svg: ^1.1.0
  string_validator: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/app/core/utils/countries.json

  fonts:
    - family: Cocon
      fonts:
        - asset: assets/fonts/Cocon-Regular.otf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf